In [ ]:
# Importamos las librerías con las que vamos a trabajar
import numpy as np
import pandas as pd

# 0.Creación de arrays

In [ ]:
# A través de una lista
lista = [1, 2, 3, 4, 5]
array_from_list = np.array(lista)
print(array_from_list)

[1 2 3 4 5]


In [ ]:
# Usando la función rand()
random_array = np.random.rand(5)  # Array de 5 valores aleatorios entre 0 y 1
print(random_array)

[0.2912279  0.86789785 0.05139574 0.03775731 0.02257473]


In [ ]:
# Usando las funciones de zeros y ones
zeros_array = np.zeros((3, 4))   # Array de zeros 3x4
ones_array = np.ones((2, 2))     # Array de unos 2x2

print("Array de zeros:")
print(zeros_array)
print("Array de unos:")
print(ones_array)

Array de zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array de unos:
[[1. 1.]
 [1. 1.]]


In [ ]:
# Crear un array de números espaciados uniformemente
start = 0
end = 10
step = 2
evenly_spaced_array = np.arange(start, end, step)
print(evenly_spaced_array)

[0 2 4 6 8]


In [ ]:
# Probar lo anterior con linspace()
print(np.linspace(0,10,2))

[ 0. 10.]


In [ ]:
#randint

# 1.Consulta del tamaño y tipo de dato (casting)

In [ ]:
ones_array.shape[0]*ones_array.shape[1]==ones_array.size

True

In [ ]:
# La forma del ones_array
ones_array.shape

(2, 2)

In [ ]:
# El número de items del array
ones_array.size

4

In [ ]:
# Consultamos la tipología de los datos del array
ones_array.dtype

dtype('float64')

In [ ]:
# Añadimos una fila al array de strings y consultamos la tipología del dato
x = np.vstack([ones_array, ['a','b']])
print(x)
print(x.dtype)

[['1.0' '1.0']
 ['1.0' '1.0']
 ['a' 'b']]
<U32


In [ ]:
# Convertimos el array random_array a entero
y = random_array.astype(int)
y

array([0, 0, 0, 0, 0])

In [ ]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
np.linspace(0,10,20).astype(int)

array([ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,
        8,  9, 10])

# 2.Ejemplos varios

## Café

In [ ]:
# Generar una distribución de teórica de pesos de paquetes de café con media 500gr y std 20gr, el tamaño muestral es 100
media_teorica = 500  # Media teórica en gramos
desviacion_estandar = 20  # Desviación estándar en gramos
tamano_muestra = 100  # Tamaño de la muestra medida en la fábrica

# Generar distribución teórica y muestra de fábrica
distribucion_teorica = np.random.normal(media_teorica, desviacion_estandar, tamano_muestra)
distribucion_teorica

array([501.88569961, 496.50999904, 521.38962005, 499.33354811,
       491.05785676, 476.37219682, 508.25384888, 502.20013056,
       498.59466265, 508.91718075, 521.88449675, 485.93017986,
       480.70569063, 476.55596699, 492.26809237, 516.92411836,
       511.77983125, 487.04412648, 512.61726519, 498.36267348,
       507.87085322, 499.28421101, 514.83182195, 527.37276158,
       524.68416272, 488.75469567, 516.56195636, 519.6132817 ,
       540.58524516, 458.16057929, 516.04070972, 528.71014677,
       513.23777605, 509.8478927 , 495.74269553, 497.24253727,
       477.77930308, 484.64090374, 487.17914161, 497.54363585,
       487.38655369, 467.90685569, 520.69051409, 498.38459024,
       492.28891501, 495.24373264, 526.16701548, 504.92912391,
       498.8302811 , 495.6616837 , 491.85115883, 523.99892657,
       527.59565829, 524.26911535, 489.42395419, 495.10958424,
       495.93687071, 480.27468089, 514.83234463, 484.80286824,
       484.52019151, 501.80404952, 493.36997531, 551.06

In [ ]:
# Media y desviación estándar medida sobre la distribución teórica
print(np.mean(distribucion_teorica))
print(np.std(distribucion_teorica))

502.4538907111746
18.215159543515302


In [ ]:
# Vuelve a medir la media y desviación con un tamaño muestral 10 veces superior

## Ruleta

In [ ]:
# Definir los colores y sus probabilidades
colores = ['R', 'B', 'Z']  # R: Rojo, B: Negro, Z: Cero
probabilidades = [18/37, 18/37, 1/37]  # Probabilidades correspondientes

# Simular 100 tiradas en la ruleta
tiradas = np.random.choice(colores, size=100, p=probabilidades)
tiradas

array(['R', 'R', 'R', 'R', 'R', 'R', 'R', 'B', 'R', 'R', 'R', 'R', 'B',
       'B', 'B', 'R', 'Z', 'R', 'R', 'B', 'B', 'B', 'R', 'R', 'R', 'R',
       'R', 'R', 'B', 'R', 'R', 'R', 'B', 'R', 'R', 'R', 'B', 'R', 'B',
       'R', 'B', 'R', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'R', 'B', 'R',
       'B', 'R', 'R', 'B', 'B', 'B', 'R', 'B', 'B', 'R', 'R', 'R', 'B',
       'B', 'B', 'R', 'B', 'B', 'R', 'R', 'B', 'R', 'B', 'R', 'B', 'B',
       'R', 'B', 'B', 'B', 'R', 'R', 'B', 'B', 'B', 'R', 'B', 'B', 'B',
       'B', 'R', 'B', 'B', 'B', 'B', 'R', 'R', 'B'], dtype='<U1')

In [ ]:
tiradas == 'R'

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False, False, False,  True, False,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
       False,  True, False,  True, False,  True, False, False, False,
       False, False, False, False,  True, False,  True, False,  True,
        True, False, False, False,  True, False, False,  True,  True,
        True, False, False, False,  True, False, False,  True,  True,
       False,  True, False,  True, False, False,  True, False, False,
       False,  True,  True, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False,  True,  True,
       False])

In [ ]:
# Contar las apariciones de cada color
apariciones = {
    'R': np.count_nonzero(tiradas == 'R'),
    'B': np.count_nonzero(tiradas == 'B'),
    'Z': np.count_nonzero(tiradas == 'Z')
}

# Imprimir resultados
for color, cantidad in apariciones.items():
    print(f"Apariciones de {color}: {cantidad}")

Apariciones de R: 49
Apariciones de B: 50
Apariciones de Z: 1


In [ ]:
# Qué color ha aparecido más veces en todas las tiradas?
vals, counts = np.unique(tiradas, return_counts=True)
print(vals, counts)
ind = np.argmax(counts)
print(ind)
print(vals[ind])

['B' 'R' 'Z'] [50 49  1]
0
B


## Notas de alumnos

In [ ]:
# Crea un array que represente las calificaciones de 15 alumnos
notas = np.random.uniform(0, 10, size=15)
notas

array([7.66429297, 7.74007447, 4.70218305, 6.68055112, 5.40775035,
       6.94251859, 0.51210854, 8.5061734 , 7.93570099, 7.2061457 ,
       5.26719059, 7.72610824, 5.70165268, 4.68540039, 2.38880265])

In [ ]:
# Redondea todas las notas a dos decimales
notas_round = np.round(notas,2)
notas_round

array([7.66, 7.74, 4.7 , 6.68, 5.41, 6.94, 0.51, 8.51, 7.94, 7.21, 5.27,
       7.73, 5.7 , 4.69, 2.39])

In [ ]:
# Cual es la nota media de los alumnos
nota_media = np.mean(notas_round)
nota_media

5.938666666666667

In [ ]:
# Cuantos alumnos rinden por debajo de la media sum() o count_nonzero()
np.sum(notas_round<nota_media)

7

In [ ]:
# Cual es el porcentaje de alumnos que han aprobado
(np.count_nonzero(notas_round>=5)/len(notas_round))*100

73.33333333333333

In [ ]:
# Muestra el top 5 de las mejores notas
np.sort(notas_round)[::-1][:5]

array([8.51, 7.94, 7.74, 7.73, 7.66])

# 3.Creación de dataframes

In [ ]:
# Crear un DataFrame a partir de un diccionario
data = {'Nombre': ['Juan', 'María', 'Luis'],
        'Edad': [25, 28, 22]}

df = pd.DataFrame(data)
print(df)

  Nombre  Edad
0   Juan    25
1  María    28
2   Luis    22


In [ ]:
# Crear un DataFrame a partir de una lista de listas
data = [['Juan', 25], ['María', 28], ['Luis', 22]]

df = pd.DataFrame(data, columns=['Nombre', 'Edad'])
print(df)

  Nombre  Edad
0   Juan    25
1  María    28
2   Luis    22


In [ ]:
# También leyendo archivos

#4.Creación de un dataframe que contenga, dni, nombres, apellidos de alumnos, notas de una asignatura.

In [ ]:
# Crear la lista de nombres
ls_nombres = ['Juan','Ricardo','Sofía','Manuel','Alexander']
# Crear la lista de apellidos
ls_apellidos = ['López Ramirez', 'López Ahumada','Gutiérrez Sánchez','Ramírez Ramírez','López Enríquez']
# Crear el array de nota usando rand()
ls_notas = list(np.round(np.random.uniform(0,10,5),2))
# Crear lista de DNIs
ls_dni = ['12345A','12346B','12347C','12348D','12349C']

In [ ]:
df_notas = pd.DataFrame(dict(DNI = ls_dni, Nombre = ls_nombres, Apellidos = ls_apellidos, Calificacion = ls_notas))

In [ ]:
# Muestra los dos primeros alumnos
df_notas.head(2)

DNI   Nombre      Apellidos  Calificacion
0  12345A     Juan  López Ramirez          8.02
1  12346B  Ricardo  López Ahumada          2.54

In [ ]:
# Muestra los dos últimos alumnos
df_notas.tail(2)

DNI     Nombre        Apellidos  Calificacion
3  12348D     Manuel  Ramírez Ramírez          8.67
4  12349C  Alexander   López Enríquez          2.21

In [ ]:
# Muestra la tipología de los datos contenidos en el df
df_notas.dtypes

DNI              object
Nombre           object
Apellidos        object
Calificacion    float64
Aprobado           bool
dtype: object

In [ ]:
# Muestra aquellos alumnos cuya nota obtenida es un aprobado
df_notas[df_notas.Calificacion>5]

DNI  Nombre        Apellidos  Calificacion
0  12345A    Juan    López Ramirez          8.02
3  12348D  Manuel  Ramírez Ramírez          8.67

In [ ]:
# Muestra los DNIs de los alunmos que han obtenido una calificación inferior a la nota media de la clase
df_notas[df_notas.Calificacion<df_notas.Calificacion.mean()]['DNI']

1    12346B
2    12347C
4    12349C
Name: DNI, dtype: object

In [ ]:
# Crea una nueva columna que se llame Aprobado y tome valor verdadero si la nota es >=5 y falso en caso contrario
df_notas['Aprobado'] = df_notas['Calificacion'].apply(lambda x: True if x>=5 else False)

In [ ]:
# Establece como indice del dataframe los dni de los alumnos
df_notas.set_index('DNI', drop=True, inplace=True)

In [ ]:
df_notas

Nombre          Apellidos  Calificacion  Aprobado  Grupo
DNI                                                                
12345A       Juan      López Ramirez          8.02      True      2
12346B    Ricardo      López Ahumada          2.54     False      1
12347C      Sofía  Gutiérrez Sánchez          0.57     False      2
12348D     Manuel    Ramírez Ramírez          8.67      True      1
12349C  Alexander     López Enríquez          2.21     False      2

In [ ]:
# Vamos a crear dos grupos para un exámen y el criterio será: Grupo 1 si el dni es un número par, Grupo 2 si el dni es impar
df_notas['Grupo'] = pd.Series(df_notas.index).apply(lambda x: 1 if int(x[:-1])%2==0 else 2).values

In [ ]:
df_notas

Nombre          Apellidos  Calificacion  Aprobado  Grupo
DNI                                                                
12345A       Juan      López Ramirez          8.02      True      2
12346B    Ricardo      López Ahumada          2.54     False      1
12347C      Sofía  Gutiérrez Sánchez          0.57     False      2
12348D     Manuel    Ramírez Ramírez          8.67      True      1
12349C  Alexander     López Enríquez          2.21     False      2

In [ ]:
# Muestra los alumnos que aprobaron y que pertenecen al grupo 2
df_notas[(df_notas.Aprobado==True)&(df_notas.Grupo==2)]

Nombre      Apellidos  Calificacion  Aprobado  Grupo
DNI                                                        
12345A   Juan  López Ramirez          8.02      True      2

In [ ]:
# Muestra los alumnos que aprobaron y que pertenecen al grupo 2 o que pertenecen a la familia López
df_notas[((df_notas.Aprobado==True)&(df_notas.Grupo==2))|(df_notas['Apellidos'].str.contains('López'))]

Nombre       Apellidos  Calificacion  Aprobado  Grupo
DNI                                                             
12345A       Juan   López Ramirez          8.02      True      2
12346B    Ricardo   López Ahumada          2.54     False      1
12349C  Alexander  López Enríquez          2.21     False      2

In [ ]:
# Incrementa en uno la calificación de los alumnos que pertenecen a la familia Gutiérrez y Ahumada
df_notas.loc[df_notas['Apellidos'].isin(['Gutiérrez', 'Ahumada']), 'Calificacion'] += 1

In [ ]:
# Muestra la info del alumno cuyo dni es 12345A
df_notas.loc['12345A']

Nombre                   Juan
Apellidos       López Ramirez
Calificacion             8.02
Aprobado                 True
Grupo                       2
Name: 12345A, dtype: object

In [ ]:
# Exporta el dataframe en formato csv separado por ;
df_notas.to_csv('notas.csv', sep=';', index=True)

In [ ]:
# Carga el archivo csv que acabamos de generar teniendo en cuenta que el DNI es el index
df_new = pd.read_csv('notas.csv', sep=';', index_col='DNI')
df_new

Nombre          Apellidos  Calificacion  Aprobado  Grupo
DNI                                                                
12345A       Juan      López Ramirez          8.02      True      2
12346B    Ricardo      López Ahumada          2.54     False      1
12347C      Sofía  Gutiérrez Sánchez          0.57     False      2
12348D     Manuel    Ramírez Ramírez          8.67      True      1
12349C  Alexander     López Enríquez          2.21     False      2